stages:
  - clean_build_run

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

services:
  - docker:dind

variables:
  # 镜像名称
  TAG: vue-cicd-demo
  # 容器名称
  CONTAINER_NAME: cicdd-v1.0.0
  PORT: 8088

# 清理镜像
job_clean_build_run:
  stage: clean_build_run
  only:
    - master
  tags:
    - tiny
  script:
    # 构件镜像
    - docker build -t $TAG .
    # 删除容器
    - docker rm -f $CONTAINER_NAME || true
    # 运行容器
    - docker run -d --name $CONTAINER_NAME -p $PORT:80 $TAG
    # 删除none镜像
    - docker images|grep none|awk '{print $3}'|xargs docker rmi
