stages:
  - deploy

cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
    - node_modules/

deploy:
  image: node:latest
  stage: deploy
  only:
    - master
  tags:
    - tiny1
  script:
    - npm install
    - npm run build
    - cp -R dist/ /root/docker/nginx/www
  artifacts:
    expire_in: 1 week
    paths:
      - dist
