stages:
  - install
  - build
  - deploy

image: node:latest

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - dist/

vue-install:
  stage: install
  only:
    - master
  script:
    # 安装依赖
    - echo "========安装依赖开始======="
    - npm install --registry=https://registry.npm.taobao.org
    - echo "========安装依赖结束======="
  tags:
    - tiny

vue-build:
  stage: build
  script:
    - echo "========编译开始======="
    - npm run build
    - echo "========编译结束======="
  tags:
    - tiny

vue-deploy:
  stage: deploy
  script:
    - echo "========部署开始======="
    - npm run deploy
    - echo "========部署结束======="
  tags:
    - tiny
